package org.example.rulebased.cachepattern.ruleunit;
unit OrderChargeRuleUnit;


rule "OrderCharge Calculation"
    when
        $o: /order;
    then
        // System.out.println($o.productId());
        int price = productCacheService.get($o.productId()).price;
        int value = $o.orderQuantity() * price;
        orderCharge.append(new OrderCharge(value));
end

query FindOrderCharge
    $o: /orderCharge;
end
