package org.example.rulebased.cachepattern.ruleunit;
unit OrderAmountRuleUnit;


rule "OrderAmount Calculation"
    when
        $o: /order;
    then
        // System.out.println($o.productId());
        int price = productCacheService.get($o.productId()).price;
        int value = $o.orderQuantity() * price;
        orderAmount.append(new OrderAmount(value));
end

query FindOrderAmount
    $o: /orderAmount;
end
